# Generated by Django 5.2.5 on 2025-09-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_view', 'Can view article'), ('can_create', 'Can create article'), ('can_edit', 'Can edit article'), ('can_delete', 'Can delete article')],
            },
        ),
    ]
